name: Build Minecraft Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # JDK 23 사용

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # JDK 23 사용
          mvn: 'true'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod-file
          path: target/*.jar
